"""updated cache column to pickletype

Revision ID: 2ec368bf1e76
Revises: 604191841d32
Create Date: 2025-05-25 17:34:47.986634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec368bf1e76'
down_revision = '604191841d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_cache', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.PickleType(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_cache', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.PickleType(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
