"""Update User model with profile and payment fields

Revision ID: 527ded7bcca9
Revises: 2ec368bf1e76
Create Date: 2025-05-26 02:12:37.850120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527ded7bcca9'
down_revision = '2ec368bf1e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('billing_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_info', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_stripe_customer_id'), ['stripe_customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_stripe_customer_id'), type_='unique')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('payment_info')
        batch_op.drop_column('billing_address')
        batch_op.drop_column('theme')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
