"""Add status, order_type, and limit_price to trades

Revision ID: 5d5a344b217d
Revises: f27f49fdaf16
Create Date: 2025-05-23 20:55:40.720690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5a344b217d'
down_revision = 'f27f49fdaf16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('order_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('limit_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('limit_price')
        batch_op.drop_column('order_type')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
