"""Add price_cache table

Revision ID: 604191841d32
Revises: d01974ec5672
Create Date: 2025-05-25 16:40:44.315542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604191841d32'
down_revision = 'd01974ec5672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coingecko_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_cache'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_cache')
    # ### end Alembic commands ###
