"""Add coingecko_id to Crypto

Revision ID: c4d1ce3c4e78
Revises: 5d5a344b217d
Create Date: 2025-05-23 21:38:52.903972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d1ce3c4e78'
down_revision = '5d5a344b217d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coingecko_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptos', schema=None) as batch_op:
        batch_op.drop_column('coingecko_id')

    # ### end Alembic commands ###
