"""Add trading/order fields and trading logic

Revision ID: cf8177402384
Revises: 527ded7bcca9
Create Date: 2025-05-26 03:51:49.681566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8177402384'
down_revision = '527ded7bcca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('market_cap', sa.Float(), nullable=True))
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('price')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_at_trade', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stop_price', sa.Float(), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_constraint('fk_trades_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_trades_crypto_id_cryptos', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trades_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_trades_crypto_id_cryptos'), 'cryptos', ['crypto_id'], ['id'])
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_trades_crypto_id_cryptos'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_trades_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_trades_crypto_id_cryptos', 'cryptos', ['crypto_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_trades_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('stop_price')
        batch_op.drop_column('price_at_trade')
        batch_op.drop_column('amount')
        batch_op.drop_column('action')

    with op.batch_alter_table('cryptos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('market_cap')
        batch_op.drop_column('current_price')

    # ### end Alembic commands ###
